disabled = false
languageCode = "fi"
languageName = "Finnish"
weight = 2
title = "hersymispiste"

[params]
#displayName = "FI"
isoCode = "fi"
rtl = false
dateFormat = "2 January 2006"
logo = "img/hersy_ico_.png"
secondaryLogo = "img/hersy_ico_.png"
disableLanguageSwitcher = true


[[params.author.links]]
patreon = "https://patreon.com/hersymispiste"

[[params.author.links]]
lingonperry = "https://app.lingonperry.com/artist/hersymispiste/be-a-fan/f09b89ff-a86a-4e9f-88a9-59fe92f8847b/2de3201d-033a-4aab-a175-6df7709e1f3e/supporter"

[[params.author.links]]
youtube = "https://www.youtube.com/@hersymispiste"

[[params.author.links]]
instagram = "https://www.instagram.com/hersymispiste/"

["params.author"]
name = "hersymispiste"
image = "img/hk.png"